deploy:
  provider: heroku
  api_key:
    secure: uAI0Gu038IwWd2X4dX5quFp0PXPCa0qn1HJOSoXMH++wNp4jlLseHUP0l+9+ui9mFBcMF1ber0kxBC5TpmNfJ2uAx4W4p9Om3LUaI26HDSrutZPU2ZRjxFt+4jGQ8xDdaSvmjbKItBf6xOWWYR87cjiVhsh00UVz0va77HihGeBFJrOgoah/pLffkLgTlwRD9fys3GPTuzaAJAaxYfZ2POzplWXTh0pNPRWr6ZXLSxOinjcSVZg21+n3iMMtvPcscDYRfLmTvKUw6PoGUlA23LAIX12r06V3fqufmPBma3pdJpDr1ARJd5Qv1EU9kOMxnQLzgLSbsowGoA8W4QbFdpZaKxUDmLPzcqf5WGlpTweuTWJRgqnjVd7O7efOunfyWHZij2ESgo1kAjMX0mOc3wfnAaN8LOBMFLY4SN8CLbRHBhMQrIQ3CrS1wnSa/nkmx2E1EXZtN8XfUk5Hn0X2MEs8+vHB+pnENwikG+gQNTdurcEkwn0VHZGfvWlRDbKNwNJP5dPkrFrEYzi0K+uCf9/mFUnUEnjEYLIJw8sH3JDiU8U4vsIzN+wTmEfNAiyksiDsXWuCBv8xgtbRwTXCAN3v+gAEK7rBUChoupojG2r/gTWFMT2277NTA2FeojpeEOZiIoRpxLdoQgmZNIuWuaxCzERrXPbsAd2m6H1891E=
  app: react-book-shelf
  on:
    repo: matteprg/react-book-shelf
